-- =============================================================================
-- Add article_brief — short card-face brief (40-60 words) distinct from
-- balanced_summary (100-120 words). Generated by the article processor alongside
-- the other summary fields.
-- =============================================================================

ALTER TABLE articles          ADD COLUMN IF NOT EXISTS article_brief text;
ALTER TABLE approved_articles ADD COLUMN IF NOT EXISTS article_brief text;
